name: Deploy to Production via SSH Commands

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy-server-1:
    name: Deploy to Server 1
    uses: ./.github/workflows/deploy-cpanel-template.yml
    with:
      server_name: "Server 1"
      port: 45022
    secrets:
      SSH_HOST: ${{ secrets.SSH_HOST }}
      SSH_USERNAME: ${{ secrets.SSH_USERNAME }}
      SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
      SSH_PASSPHRASE: ${{ secrets.SSH_PASSPHRASE }}
      DIR: ${{ secrets.DIR }}
      GH_REPOSITORY: ${{ secrets.GH_REPOSITORY }}
      GH_TOKEN: ${{ secrets.GH_TOKEN }}

  deploy-server-2:
    name: Deploy to Server 2
    uses: ./.github/workflows/deploy-cpanel-template.yml
    with:
      server_name: "Server 2"
      port: 45022
    secrets:
      SSH_HOST: ${{ secrets.SSH_HOST_2 }}
      SSH_USERNAME: ${{ secrets.SSH_USERNAME_2 }}
      SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY_2 || secrets.SSH_PRIVATE_KEY }}
      SSH_PASSPHRASE: ${{ secrets.SSH_PASSPHRASE_2 || secrets.SSH_PASSPHRASE }}
      DIR: ${{ secrets.DIR_2 }}
      GH_REPOSITORY: ${{ secrets.GH_REPOSITORY }}
      GH_TOKEN: ${{ secrets.GH_TOKEN }}